projects/forms.py
from wtforms import Form, StringField, TextAreaField, SelectField, DateField


class ProjectForm(Form):
    """
    Class ProjectForm
    """
    name = StringField('Name')
    description = TextAreaField('Description')
    quantity_participants = SelectField(u'Quantity of participants',
                                        choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])


class TaskForm(Form):
    """
    Class TaskForm
    """
    title = StringField('Title')
    description = TextAreaField('Description')
    role = StringField('Role')
    deadline = DateField('DeadLine')  # format='%Y-%m-%d'
    artefacts = StringField('Artefacts')

projects/blueprint.py
import traceback

from flask import Blueprint, request, redirect, url_for
from flask import render_template
from .forms import ProjectForm, TaskForm
from flask_security import current_user

from app import db
from models import Post, Tag, User, Project, Task
from flask_security import login_required

projects = Blueprint('projects', __name__, template_folder='templates', static_url_path='projects')


@projects.route('/')
@login_required
def index():
    """Index function, which return index project page """

    return render_template('projects/index.html',
                           projects=User.query.filter(User.email == current_user.email).first().projects)


@projects.route('/create_project', methods=['GET', 'POST'])
@login_required
def create_project():
    """Create project function, which return form to create project"""

    if request.method == 'POST':
        name = request.form['name']
        description = request.form['description']
        quantity_participants = request.form['quantity_participants']
        try:
            user = User.query.filter(User.email == current_user.email).first()
            project = Project(name=name, description=description, quantity_participants=quantity_participants,
                              created_by=user.email)
            user.projects.append(project)
            db.session.add_all([project, user])
            db.session.commit()
            return redirect(url_for('projects.index'))
        except:
            print('Something went wrong')
            print(traceback.format_exc())
            return '<h1>Something went wrong<h1>' + traceback.format_exc()
    form = ProjectForm()
    return render_template('projects/create_project.html', form=form)


@projects.route('/<slug>')
def project_info(slug):
    """Project info, which return info page to this project"""

    project = Project.query.filter(Project.slug == slug).first_or_404()
    if project:
        return render_template('projects/project_info.html', project=project)
    else:
        return "<h1>This project is not exist</h1>"


@projects.route('/<slug>/tasks')
def tasks(slug):
    """Tasks in this project, where author can create tasks and user can tke this task"""

    project = Project.query.filter(Project.slug == slug).first_or_404()
    if project:
        return render_template('projects/project_tasks.html', project=project)
    else:
        return "<h1>This project is not exist</h1>"


@projects.route('/<slug>/tasks/<slug_task>', methods=['GET', 'POST'])
@login_required
def task_detail(slug, slug_task):
    """Info about this task"""

    project = Project.query.filter(Project.slug == slug).first_or_404()
    tasks = project.tasks
    task = False
    for i in tasks:
        if i.slug == slug_task:
            task = i

    if request.method == 'POST':
        try:
            task = Task.query.filter(Task.slug == slug_task).first()
            task.user_email = current_user.email
            db.session.add(task)
            db.session.commit()
        except:
            print(traceback.format_exc())

    if project and task:
        artefacts_string: str = task.artefacts
        artefacts = artefacts_string.split()
        return render_template('projects/task_detail.html', project=project, task=task, artefacts=artefacts)
    else:
        return "<h1>This project or/and task is/are not exist</h1>"


@projects.route('/<slug>/users', methods=['GET', 'POST'])
def users(slug):
    """All users in this project. Here user can join to the project if quantity of participants allow this"""

    project = Project.query.filter(Project.slug == slug).first_or_404()

    if request.method == 'POST':
        try:
            if current_user.is_anonymous:
                return redirect(url_for('login_page') + '?next=' + request.url)

            if len(project.users.all()) < project.quantity_participants:
                user = User.query.filter(User.email == current_user.email).first()
                user.projects += [project]
                db.session.add(user)
                db.session.commit()
        except:
            print(traceback.format_exc())
    if project:
        return render_template('projects/project_users.html', project=project)
    else:
        return "<h1>This project is not exist</h1>"


@projects.route('/<slug>/create_task', methods=['GET', 'POST'])
def create_task(slug):
    """Form to create task"""

    project = Project.query.filter_by(slug=slug).first_or_404()
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        role = request.form['role']
        deadline = request.form['deadline']
        artefacts = request.form['artefacts']
        try:
            task = Task(title=title, description=description, role=role, deadline=deadline, artefacts=artefacts)
            project.tasks.append(task)
            db.session.add_all([project, task])
            db.session.commit()
            return redirect(url_for('projects.tasks', slug=project.slug))
        except:
            print('Something went wrong')
            print(traceback.format_exc())
            return '<h1>Something went wrong<h1>' + traceback.format_exc()
    form = TaskForm()
    return render_template('projects/create_task.html', form=form, project=project)


@projects.route('/all_projects')
def all_projects():
    """All projects"""

    projects = Project.query.all()
    return render_template('projects/all_projects.html', projects=projects)

projects/templates/projects/all_projects.html
{% extends 'base.html' %}

{% block title %}
    All projects
{% endblock %}


{% block content_title %}
    Projects
{% endblock %}

{% block main %}
    {% for project in projects %}
        <p>
            <a href="{{ url_for('projects.project_info', slug=project.slug) }}">{{ project.name }}</a>
        </p>
    {% endfor %}
{% endblock %}

projects/templates/projects/create_project.html
{% extends 'base.html' %}

{% block title %}
    Create Project
{% endblock %}


{% block main %}
        <form action="{{ url_for('projects.create_project') }}" method="post">
            {% for field in form %}
                    {{ field.label() }}
{#                    {{ field.label(class='control-label') }}#}
{#                    {{ field(class='form-control') }}#}
                    {{ field() }}
            {% endfor %}
            <button type="submit">Create Project</button>
        </form>
{% endblock %}

projects/templates/projects/create_task.html
{% extends 'base.html' %}

{% block title %}
    Create Task
{% endblock %}


{% block main %}
    <h1 style="color: black">You can create task to <i>{{ project.name }}</i>.</h1>
    <form action="{{ url_for('projects.create_task', slug=project.slug) }}" method="post">
        {% for field in form %}
            {{ field.label(style='color: red') }}
            {#                    {{ field.label(class='control-label') }}#}
            {#                    {{ field(class='form-control') }}#}
            {{ field() }}
        {% endfor %}
        <button type="submit">Create Task</button>
    </form>
{% endblock %}

projects/templates/projects/index.html
{% extends 'base.html' %}

{% block title %}
    MyProjects
{% endblock %}

{% block styles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Дополнение к теме -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    {{ super() }}

{% endblock %}

{% block main %}
    <div class="container" style="padding-top: 1%">
        <!-- Тема: Ваши проекті -->
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <nav class="navbar navbar-default">
              <p class="text-center" style="font-size: 24px; margin-top: 3%">Ваши проекты</p>
            </nav>
          </div>
        </div>

        <!-- Кнопка: Создать проект -->
        <a class="col-md-2 col-md-offset-5" style="padding-left: 0px; padding-right: 0px; padding-bottom: 1%"
          href="{{ url_for('projects.create_project') }}">
          <button type="button" class="btn btn-default btn-block">Создать проект</button>
        </a>

        <a class="col-md-2 col-md-offset-3" style="padding-left: 0px; padding-right: 0px; padding-bottom: 1%"
          href="{{ url_for('projects.all_projects') }}">
          <button type="button" class="btn btn-default btn-block">Другие проекты</button>
        </a>

        {% if not projects %}
            <p style="padding-top: 1%; padding-bottom: 1%">
                <button type="button" class="btn btn-sm btn-outline-dark btn-block">
                  <p class="text-left" style="font-size: 14px; margin-top: 10px">Нема проектов у вас!</p>
                </button>
            </p>
        {% else %}
            {% for project in projects %}
                <div style="padding-top: 2px; padding-bottom: 2px">
                  <a style="padding-top: 1%; padding-bottom: 1%" href="{{ project.slug }}">
                    <button type="button" class="btn btn-sm btn-outline-dark btn-block">
                          <p class="text-left" style="font-size: 14px; margin-top: 10px">{{ project.name }}</p>
                      </button>
                      <p> </p>
                  </a>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

projects/templates/projects/project_info.html
{% extends 'base.html' %}


{% block title %}
    {{ project.name }}
{% endblock %}


{% block styles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Дополнение к теме -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    {{ super() }}

{% endblock %}


{% block main %}
    <div class="container">

        <div class="row">
            {# Опции #}
            <div class="col-md-2" style="padding-left: 0px; padding-right: 0px">
                {# Шапка: Опции #}
                <nav class="navbar navbar-default" style="margin-bottom: 0px">
                    <p class="text-center" style="font-size: 24px; margin-top: 5px">Опции</p>
                </nav>

                {# Кнопка: Информация #}
                <a href="{{ url_for('projects.project_info', slug=project.slug) }}">
                    <button style="padding-top: 15px; padding-bottom: 15px; font-size: 18px"
                            type="button" class="btn btn-default btn-block">Информация
                    </button>
                </a>

                {# Кнопка: Задания #}
                <a href="{{ url_for('projects.tasks', slug=project.slug) }}">
                    <button style="padding-top: 15px; padding-bottom: 15px; font-size: 18px"
                            type="button" class="btn btn-default btn-block">Задания
                    </button>
                </a>

                {# Кнопка: Работники #}
                <a href="{{ url_for('projects.users', slug=project.slug) }}">
                    <button style="padding-top: 15px; padding-bottom: 15px; font-size: 18px"
                            type="button" class="btn btn-default btn-block">Работники
                    </button>
                </a>
            </div>

            {# Шапка: информация об проекте #}
            <div class="col-md-10" style="padding-left: 0px; padding-right: 0px">
                {# Шапка: информация об проекте #}
                <nav class="navbar navbar-default" style="margin-bottom: 10px">
                    <p class="text-center" style="font-size: 24px; margin-top: 5px">Информация об проекте</p>
                </nav>
                <p style="color: #000000; padding-left: 10px; font-weight: 900; font-size: 24px">Общая информация:</p>
                <p style="color: #000000; padding-left: 10px;">Название проекта: {{ project.name }}</p>
                <p style="color: #000000; padding-left: 10px;">Краткое описание: {{ project.description }}</p>
                <p style="color: #000000; padding-left: 10px;">Количество работников в
                    проекте: {{ project.quantity_participants }}</p>
                <p style="margin-bottom: 250px"></p>
            </div>
        </div>
    </div>
{% endblock %}

projects/templates/projects/project_tasks.html
{% extends 'base.html' %}

{% block title %}
    {{ project.name }}
{% endblock %}


{% block styles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    {{ super() }}

{% endblock %}


{% block main %}
    <div class="container">

        <div class="row">
            {# Опции #}
            <div class="col-md-2" style="padding-left: 0px; padding-right: 0px">
                {# Шапка: Опции #}
                <nav class="navbar navbar-default" style="margin-bottom: 0px">
                    <p class="text-center" style="font-size: 24px; margin-top: 5px">Опции</p>
                </nav>

                {# Кнопка: Информация #}
                <a href="{{ url_for('projects.project_info', slug=project.slug) }}">
                    <button style="padding-top: 15px; padding-bottom: 15px; font-size: 18px"
                            type="button" class="btn btn-default btn-block">Информация
                    </button>
                </a>

                {# Кнопка: Задания #}
                <a href="{{ url_for('projects.tasks', slug=project.slug) }}">
                    <button style="padding-top: 15px; padding-bottom: 15px; font-size: 18px"
                            type="button" class="btn btn-default btn-block">Задания
                    </button>
                </a>

                {# Кнопка: Работники #}
                <a href="{{ url_for('projects.users', slug=project.slug) }}">
                    <button style="padding-top: 15px; padding-bottom: 15px; font-size: 18px"
                            type="button" class="btn btn-default btn-block">Работники
                    </button>
                </a>
            </div>


            {# Шапка: информация о заданиях #}
            <div class="col-md-10" style="padding-left: 0px; padding-right: 0px">
                {# Шапка: информация об проекте #}
                <nav class="navbar navbar-default" style="margin-bottom: 5px">
                    <p class="text-center" style="font-size: 24px; margin-top: 5px">Информация о заданиях</p>
                </nav>

                {# Поле: общая информация и кнопка "Создать проект" #}
                <div class="row" style="margin-bottom: 3px; margin-top: 0px; padding-top: 0px">
                    <div class="col-md-4" style="margin-bottom: 0px; margin-top: 0px; padding-top: 0px">
                        <p style="color: #000000; padding-top: 5px; padding-left: 10px; font-weight: 900; font-size: 24px">
                            Задания проекта:</p>
                    </div>

                    {% if current_user.email == project.created_by %}
                        <div class="col-md-3 col-md-offset-5"
                             style="margin-bottom: 1px; margin-top: 1px; padding-top: 0px">
                            <a href="{{ url_for('projects.create_task',slug=project.slug) }}">
                                <button style="margin-top: 0px; padding-top: 10px; padding-bottom: 10px; font-size: 18px"
                                        type="button" class="btn btn-default btn-block">Создать задание
                                </button>
                            </a>
                        </div>
                    {% endif %}
                </div>

                {# Поле: информация о задании: название, работник, статус #}
                <div style="padding-top: 2px; padding-bottom: 2px">
                    {% for task in project.tasks %}
                        <a href="{{ url_for('projects.task_detail', slug=project.slug, slug_task=task.slug) }}">
                            <button type="button" class="btn btn-sm btn-default btn-block">
                                <div class="row" style="padding-top: 10px; font-size: 16px; font-weight: 600">
                                    <div class="col-md-4"><p style="text-align: left">{{ task.title }}</p></div>
                                    <div class="col-md-4"><p style="text-align: center">{{ task.description }}</p></div>
                                    <div class="col-md-4"><p style="text-align: right">{{ task.state }}</p></div>
                                </div>
                            </button>
                        </a>
                    {% endfor %}
                </div>

                <p style="margin-bottom: 350px"></p>
            </div>
        </div>
    </div>
{% endblock %}

projects/templates/projects/project_users.html
{% extends 'base.html' %}


{% block title %}
    {{ project.name }}
{% endblock %}


{% block styles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Дополнение к теме -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    {{ super() }}

{% endblock %}


{% block main %}
    <div class="container">

        <div class="row">
            {# Опции #}
            <div class="col-md-2" style="padding-left: 0px; padding-right: 0px">
                {# Шапка: Опции #}
                <nav class="navbar navbar-default" style="margin-bottom: 0px">
                    <p class="text-center" style="font-size: 24px; margin-top: 5px">Опции</p>
                </nav>

                {# Кнопка: Информация #}
                <a href="{{ url_for('projects.project_info', slug=project.slug) }}">
                    <button style="padding-top: 15px; padding-bottom: 15px; font-size: 18px"
                            type="button" class="btn btn-default btn-block">Информация
                    </button>
                </a>

                {# Кнопка: Задания #}
                <a href="{{ url_for('projects.tasks', slug=project.slug) }}">
                    <button style="padding-top: 15px; padding-bottom: 15px; font-size: 18px"
                            type="button" class="btn btn-default btn-block">Задания
                    </button>
                </a>

                {# Кнопка: Работники #}
                <a href="{{ url_for('projects.users', slug=project.slug) }}">
                    <button style="padding-top: 15px; padding-bottom: 15px; font-size: 18px"
                            type="button" class="btn btn-default btn-block">Работники
                    </button>
                </a>
            </div>

            {# Шапка: информация об проекте #}
            <div class="col-md-10" style="padding-left: 0px; padding-right: 0px">
                {# Шапка: информация об проекте #}
                <nav class="navbar navbar-default" style="margin-bottom: 5px">
                    <p class="text-center" style="font-size: 24px; margin-top: 5px">Информация о работниках</p>
                </nav>

                <div class="row" style="margin-bottom: 3px; margin-top: 0px; padding-top: 0px">
                    {# Поле: Работники проекта: #}
                    <div class="col-md-4" style="margin-bottom: 0px; margin-top: 0px; padding-top: 0px">
                        <p style="color: #000000; padding-top: 5px; padding-left: 10px; font-weight: 900; font-size: 24px">
                            Работники проекта:</p>
                    </div>

                    {# Кнопка "Присоединиться" для пользователей #}
                    {% if project not in current_user.projects %}

                        <div class="col-md-3 col-md-offset-5"
                             style="margin-bottom: 1px; margin-top: 1px; padding-top: 0px">
                            <form action="{{ url_for('projects.users', slug=project.slug) }}" method="post">
                                {% if project.quantity_participants<=project.users.all()|length %}
                                    <button style="margin-top: 0px; padding-top: 10px; padding-bottom: 10px; font-size: 18px"
                                            type="submit" class="btn btn-default btn-block" disabled>Max quantity of
                                        participants is {{ project.quantity_participants }}
                                    </button>
                                {% else %}
                                    <button style="margin-top: 0px; padding-top: 10px; padding-bottom: 10px; font-size: 18px"
                                            type="submit" class="btn btn-default btn-block">Join to
                                        us!
                                    </button>
                                {% endif %}
                            </form>
                        </div>
                    {% endif %}
                </div>

                <ul style="color: #000000; padding-left: 10px">{% for user in project.users %}
                    <li>{{ user.email }}</li>
                {% endfor %}
                </ul>

                <p style="margin-bottom: 350px"></p>
            </div>
        </div>
    </div>
{% endblock %}

projects/templates/projects/task_detail.html
{% extends 'base.html' %}


{% block title %}
    {{ project.name }}: {{ task.title }}
{% endblock %}


{% block styles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Дополнение к теме -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    {{ super() }}

{% endblock %}


{% block main %}
    <div class="container">

        <div class="row">
            {# Шапка: информация об проекте #}
            <nav class="navbar navbar-default" style="margin-bottom: 10px">
                <p class="text-center" style="font-size: 24px; margin-top: 5px">Информация о таске</p>
            </nav>
            <p style="color: #000000; padding-left: 10px; font-weight: 900; font-size: 24px">Общая информация:</p>
            <p style="color: #000000; padding-left: 10px;">Название таски: {{ task.title }}</p>
            <p style="color: #000000; padding-left: 10px;">Краткое описание: {{ task.description }}</p>
            <p style="color: #000000; padding-left: 10px;">Состояние таски: {{ task.state }}</p>
            <p>
                {% if not task.user_email and current_user.email not in project.created_by %}
                    <div>
                        <form action="{{ url_for('projects.task_detail', slug=project.slug, slug_task=task.slug) }}"
                              method="post">
                            <button>Take this project!
                            </button>
                        </form>
                    </div>
                {% endif %}
            </p>
            <p style="color: #000000; padding-left: 10px;">Подходящая для таски роль: {{ task.role }}</p>
            <p style="color: #000000; padding-left: 10px;">Дедлайн таски: {{ task.deadline }}</p>
            <p style="color: #000000; padding-left: 10px;">Артефакты таски: </p>
            {% for artefact in artefacts %}
                <a href="//{{ artefact }}">{{ artefact }}</a>
            {% endfor %}
            <p style="color: #000000; padding-left: 10px;">Юзер на таске: {{ task.user_email }}</p>
            <p style="color: #000000; padding-left: 10px;">Дата создания таски: {{ task.created }}</p>
            <p style="margin-bottom: 250px"></p>
        </div>
    </div>
    </div>
{% endblock %}