posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')
    tags = StringField('Enter tags with a space')

posts/blueprint.py
import traceback

from flask import Blueprint, request, redirect, url_for
from flask import render_template
from .forms import PostForm
from app import db
from models import Post, Tag
from flask_security import login_required
posts = Blueprint('posts', __name__, template_folder='templates', static_url_path='posts')


@posts.route('/')
def index():
    q = request.args.get('q')
    if q:
        posts = []
        for post in Post.query.all():
            if post not in posts:
                for tag in post.tags:
                    if tag.name.lower() == q.lower():
                        posts.append(post)
        posts += Post.query.filter(
            Post.title.contains(q) | Post.body.contains(q)).order_by(
            Post.created.desc())
    else:
        posts = Post.query.order_by(Post.created.desc())
    return render_template('posts/index.html', posts=posts)


# @posts.route('/<slug>/edit/', methods=['GET', 'POST'])
# def edit_post(slug):
#     post = Post.query.filter(Post.slug == slug).first_or_404()
#     if request.method == 'POST':
#         form = PostForm(formdata=request.form, obj=post)
#         form.populate_obj(post)
#         db.session.commit()
#
#         return redirect(url_for('posts.post_detail', slug=post.slug))
#
#     form = PostForm(obj=post)
#     return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    if post:
        tags = post.tags
        return render_template('posts/post_detail.html', post=post, tags=tags)
    else:
        return "<h1>This post is not exist</h1>"


@posts.route('/tags/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter_by(slug=slug).first_or_404()
    return render_template('posts/tag_detail.html', tag=tag, posts=tag.posts)


@posts.route('/tags')
def index_tag():
    tags = Tag.query.all()
    return render_template('posts/index_tag.html', tags=tags)


@posts.route('/create_post', methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        tags_name = request.form['tags']
        tags = []
        all_to_add = []
        for name in tags_name.split():
            tag = Tag.query.filter(Tag.name.contains(name)).first_or_404()
            if tag:
                tags += [tag]
                continue
            tag = Tag(name=name)
            all_to_add += [tag]
            tags += [tag]
        try:
            post = Post(title=title, body=body)
            post.tags = tags
            all_to_add.append(post)
            db.session.add_all(all_to_add)
            db.session.commit()
            return redirect(url_for('posts.index'))
        except:
            print('Something went wrong')
            print(traceback.format_exc())
            return '<h1>Something went wrong<h1>' + traceback.format_exc()
    form = PostForm()
    return render_template('posts/create_post.html', form=form)

projects/blueprint.py
import traceback

from flask import Blueprint, request, redirect, url_for
from flask import render_template
from .forms import ProjectForm, TaskForm
from flask_security import current_user

from app import db
from models import Post, Tag, User, Project, Task
from flask_security import login_required

projects = Blueprint('projects', __name__, template_folder='templates', static_url_path='projects')


@projects.route('/')
@login_required
def index():
    """Index function, which return index project page """

    return render_template('projects/index.html',
                           projects=User.query.filter(User.email == current_user.email).first().projects)


@projects.route('/create_project', methods=['GET', 'POST'])
@login_required
def create_project():
    """Create project function, which return form to create project"""

    if request.method == 'POST':
        name = request.form['name']
        description = request.form['description']
        quantity_participants = request.form['quantity_participants']
        try:
            user = User.query.filter(User.email == current_user.email).first()
            project = Project(name=name, description=description, quantity_participants=quantity_participants,
                              created_by=user.email)
            user.projects.append(project)
            db.session.add_all([project, user])
            db.session.commit()
            return redirect(url_for('projects.index'))
        except:
            print('Something went wrong')
            print(traceback.format_exc())
            return '<h1>Something went wrong<h1>' + traceback.format_exc()
    form = ProjectForm()
    return render_template('projects/create_project.html', form=form)


@projects.route('/<slug>')
def project_info(slug):
    """Project info, which return info page to this project"""

    project = Project.query.filter(Project.slug == slug).first_or_404()
    if project:
        return render_template('projects/project_info.html', project=project)
    else:
        return "<h1>This project is not exist</h1>"


@projects.route('/<slug>/tasks')
def tasks(slug):
    """Tasks in this project, where author can create tasks and user can tke this task"""

    project = Project.query.filter(Project.slug == slug).first_or_404()
    if project:
        return render_template('projects/project_tasks.html', project=project)
    else:
        return "<h1>This project is not exist</h1>"


@projects.route('/<slug>/tasks/<slug_task>', methods=['GET', 'POST'])
@login_required
def task_detail(slug, slug_task):
    """Info about this task"""

    project = Project.query.filter(Project.slug == slug).first_or_404()
    tasks = project.tasks
    task = False
    for i in tasks:
        if i.slug == slug_task:
            task = i

    if request.method == 'POST':
        try:
            task = Task.query.filter(Task.slug == slug_task).first()
            task.user_email = current_user.email
            db.session.add(task)
            db.session.commit()
        except:
            print(traceback.format_exc())

    if project and task:
        artefacts_string: str = task.artefacts
        artefacts = artefacts_string.split()
        return render_template('projects/task_detail.html', project=project, task=task, artefacts=artefacts)
    else:
        return "<h1>This project or/and task is/are not exist</h1>"


@projects.route('/<slug>/users', methods=['GET', 'POST'])
def users(slug):
    """All users in this project. Here user can join to the project if quantity of participants allow this"""

    project = Project.query.filter(Project.slug == slug).first_or_404()

    if request.method == 'POST':
        try:
            if current_user.is_anonymous:
                return redirect(url_for('login_page') + '?next=' + request.url)

            if len(project.users.all()) < project.quantity_participants:
                user = User.query.filter(User.email == current_user.email).first()
                user.projects += [project]
                db.session.add(user)
                db.session.commit()
        except:
            print(traceback.format_exc())
    if project:
        return render_template('projects/project_users.html', project=project)
    else:
        return "<h1>This project is not exist</h1>"


@projects.route('/<slug>/create_task', methods=['GET', 'POST'])
def create_task(slug):
    """Form to create task"""

    project = Project.query.filter_by(slug=slug).first_or_404()
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        role = request.form['role']
        deadline = request.form['deadline']
        artefacts = request.form['artefacts']
        try:
            task = Task(title=title, description=description, role=role, deadline=deadline, artefacts=artefacts)
            project.tasks.append(task)
            db.session.add_all([project, task])
            db.session.commit()
            return redirect(url_for('projects.tasks', slug=project.slug))
        except:
            print('Something went wrong')
            print(traceback.format_exc())
            return '<h1>Something went wrong<h1>' + traceback.format_exc()
    form = TaskForm()
    return render_template('projects/create_task.html', form=form, project=project)


@projects.route('/all_projects')
def all_projects():
    """All projects"""

    projects = Project.query.all()
    return render_template('projects/all_projects.html', projects=projects)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create Post
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% endblock %}

{% block content_title %}
    Here you can create your posts
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="post">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Create Post</button>
        </form>
    </div>
{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit Post
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% endblock %}

{% block content_title %}
    Edit Post
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.edit_post',slug=post.slug) }}" method="post">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Create Post</button>
        </form>
    </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index page
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}

    {% for post in posts %}

        <p>
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </p>
    {% endfor %}
    <H2><a href="{{ url_for('posts.index_tag') }}" style="color: mediumvioletred">Tags</a></H2>
    <H2><a href="{{ url_for('projects.all_projects') }}">And now projects!</a></H2>
{% endblock %}

posts/templates/posts/index_tag.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index Tag page
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% endblock %}

{% block content_title %}
    Tags
{% endblock %}

{% block content %}
    <div>
        {% for tag in tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}" class="btn btn-primary btn-lg active" role="button"
               aria-pressed="true">{{ tag.name }}</a>
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% endblock %}

{% block content_title %}
    {{ post.title }}
    <div>
        {% for tag in tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}" class="btn btn-primary btn-lg active" role="button"
               aria-pressed="true">{{ tag.name }}</a>
        {% endfor %}
    </div>
{% endblock %}

{% block content %}
    {{ post.body }}
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% endblock %}

{% block content_title %}
    Posts of "{{ tag.name }}" tag
{% endblock %}

{% block content %}
    <div>
        {% for post in posts %}
            <p>
                <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
            </p>
        {% endfor %}
    </div>
{% endblock %}